modules:
  telemetry:
    metrics:
      - name: cpu_cores
        path: '{.cpuC}'
        type: gauge

      - name: cpu_load_percent
        path: '{.cpuL}'
        type: gauge

      - name: total_ram_mb
        path: '{.tRam}'
        type: gauge

      - name: used_ram_mb
        path: '{.uRam}'
        type: gauge

      - name: disk_mb
        path: '{.disk}'
        type: gauge
